name: booking-order-app
services:
  user-service:
    container_name: field-service
    # image: qika219/user-service:1
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env